console.log(typeof 10);
console.log(typeof null);
console.log(typeof undefined);
console.log(typeof true);
console.log(typeof false);
console.log(typeof 0);
console.log(typeof 10);
console.log(typeof -0);
console.log(typeof 123n);
console.log(typeof {});
console.log(typeof [1,2,3,true, false]);
console.log(typeof function() {});
console.log(typeof NaN);
